version: '3.7'
services:
  web:
    container_name: userBlogService
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
      - mq
      - elasticsearch
      - kibana
    ports:
      - '3000:3000'
    volumes:
      - .:/server
    environment:
      RABBITMQ_URI: amqp://root:root@mq:5672
      RABBITMQ_QUEUE: blog_queue
      MONGO_URI: mongodb://db:27017/userBlog
      JWT_SECRET: JwtSecretTokenWillBeHere
      JWT_EXPIRATION: 8h
      ELASTIC_SEARCH_NODE: http://elasticsearch:9200
      INDICES: blog_category
      REDIS_URL: redis://userBlogServiceRedis:6379
      PORT: 3000

  # Database
  db:
    container_name: userBlogServiceMongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always

  # Message Queue Server
  mq:
    container_name: userBlogServiceRabbitMQ
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - '5672:5672'
      - '15672:15672'

  # Redis Server
  redisCache:
    container_name: userBlogServiceRedis
    image: redis:alpine
    environment:
      FLASK_ENV: development
    ports:
      - '6379:6379'
    volumes:
      - ./config/redis.conf:/redis.conf

  # ElasticSearch
  elasticsearch:
    container_name: userBlogServiceElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms2G -Xmx2G'
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    expose:
      - '9200'
    networks:
      - elastic

  # Kibana
  kibana:
    container_name: userBlogServiceKibana
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.8.4
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    expose:
      - '5601'
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
